#!/usr/bin/env python3
"""Convert PNG assets to RGB565 C++ sources for TFT pushPixels (byte-swapped)."""

import argparse
import re
import sys
from pathlib import Path

from PIL import Image


def rgba_to_rgb565(r, g, b):
    rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return ((rgb565 & 0x00FF) << 8) | ((rgb565 & 0xFF00) >> 8)


def stem_to_prefix(stem: str) -> str:
    """e.g. space-left -> space_left for aImageWidth-style symbols."""
    prefix = re.sub(r"[^a-zA-Z0-9_]", "_", stem.replace("-", "_"))
    if prefix and prefix[0].isdigit():
        prefix = "key_" + prefix
    return prefix


def convert_png(input_path: Path, output_dir: Path, prefix: str | None = None) -> str:
    if prefix is None:
        prefix = stem_to_prefix(input_path.stem)

    with Image.open(input_path) as img:
        img = img.convert("RGB")
        width, height = img.size
        pixels = list(img.getdata())

    symbol = f"{prefix}Image"
    header_path = output_dir / f"{prefix}_image.h"
    source_path = output_dir / f"{prefix}_image.cpp"

    header_path.write_text(
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        f"extern const uint16_t {symbol}Width;\n"
        f"extern const uint16_t {symbol}Height;\n\n"
        f"extern const uint16_t {symbol}Data[];\n",
        encoding="utf-8",
    )

    lines = ["#include <cstdint>\n", f'#include "{prefix}_image.h"\n\n']
    lines.append(f"const uint16_t {symbol}Width = {width};\n")
    lines.append(f"const uint16_t {symbol}Height = {height};\n\n")
    lines.append(f"const uint16_t {symbol}Data[] = {{\n")

    for y in range(height):
        row_parts = []
        for x in range(width):
            r, g, b = pixels[y * width + x]
            rgb565 = rgba_to_rgb565(r, g, b)
            row_parts.append(f"0x{rgb565:04x}")
        lines.append(", ".join(row_parts) + ",\n")

    lines.append("};\n")
    source_path.write_text("".join(lines), encoding="utf-8")
    return prefix


def convert_directory(input_dir: Path, output_dir: Path) -> list[str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    prefixes = []
    for png in sorted(input_dir.glob("*.png")):
        prefix = convert_png(png, output_dir)
        prefixes.append(prefix)
        print(f"  {png.name} -> {prefix}_image.{{h,cpp}} ({prefix}ImageWidth x Height)")

    manifest = output_dir / "keyboard_images.h"
    includes = "\n".join(f'#include "{p}_image.h"' for p in prefixes)
    manifest.write_text(
        "#pragma once\n\n"
        "// Auto-generated by utils/png_converter.py — do not edit by hand.\n\n"
        f"{includes}\n",
        encoding="utf-8",
    )
    print(f"Wrote manifest {manifest} ({len(prefixes)} images)")
    return prefixes


def main():
    parser = argparse.ArgumentParser(description="Convert PNG to RGB565 firmware image sources.")
    parser.add_argument("input", nargs="?", help="PNG file or directory (with --batch)")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output directory (default: firmware/src/Screens/images/keyboard for batch)",
    )
    parser.add_argument(
        "--batch",
        action="store_true",
        help="Convert every *.png in input directory",
    )
    args = parser.parse_args()

    if not args.input:
        parser.print_help()
        sys.exit(1)

    input_path = Path(args.input)
    if args.batch or input_path.is_dir():
        if not input_path.is_dir():
            print(f"Not a directory: {input_path}")
            sys.exit(1)
        output_dir = args.output or Path("firmware/src/Screens/images/keyboard")
        print(f"Converting {input_path} -> {output_dir}")
        convert_directory(input_path, output_dir)
        return

    output_dir = args.output or Path(".")
    output_dir.mkdir(parents=True, exist_ok=True)
    prefix = convert_png(input_path, output_dir)
    print(f"Conversion completed: {prefix}_image.h / {prefix}_image.cpp")


if __name__ == "__main__":
    main()
